site_name: Cross-System JetStream Migration
site_url: https://synadia-labs.github.io/cross-system-jetstream-migration
repo_url: https://github.com/synadia-labs/cross-system-jetstream-migration
repo_name: cross-system-jetstream-migration

plugins:
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  custom_dir: overrides
  favicon: static/favicon.png
  logo: static/favicon.png
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer

extra:
  analytics:
    provider: custom

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Steps:
    - Local: local.md
    - Leaf: leaf.md
    - Cloud: cloud.md
    - Summary: summary.md
  - Resources: resources.md
